[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.3"

WIFI_SSID = ""
WIFI_PASSWORD = ""

MQTT_BROKER = "mqtt://192.168.1.216:1883"
MQTT_CLIENT_ID = "Lock-n-Roll"
MQTT_COMMAND_TOPIC = "dk/sdu/mmmi/project/command"
MQTT_HEARTBEAT_TOPIC = "dk/sdu/mmmi/project/heartbeat"
MQTT_HEARTBEAT_FREQUENCY_MS = "1000"
